web-app/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from linkage.shared import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', view=views.about_view, name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('linkage.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Dataset exploration
    url(r'^datasets/', include('linkage.datasets.urls', namespace='datasets')),

    # Datsets Linking
    url(r'^linking/', include('linkage.linking.urls', namespace='linking')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=settings.SHOW_INDEXES)
#show indexs are for dev debugging purposes

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

web-app/linkage/datasets/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from linkage.datasets import views

urlpatterns = [
    url(
        regex=r'^preview/$',
        view=views.dataset_preview,
        name='get_preview'
    ),
    url(
        regex=r'^header/$',
        view=views.dataset_header,
        name='header'
    ),
    url(
        regex=r'^$',
        view=views.DatasetListView.as_view(),
        name='list'
    ),
    url(
        regex=r'add/$',
        view=views.DatasetCreateView.as_view(),
        name='add'
    ),
    url(
        regex=r'edit/(?P<pk>[0-9]+)/$',
        view=views.DatasetUpdateView.as_view(),
        name='edit'
    ),
    url(
        regex=r'delete/(?P<pk>[0-9]+)/$',
        view=views.DatasetDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^(?P<pk>[0-9]+)/$',
        view=views.DatasetDetailView.as_view(),
        name='detail'
    ),
 ]

web-app/linkage/linking/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from linkage.linking import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.LinkingProjectListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^status/$',
        view=views.AjaxListView.as_view(),
        name='status'
    ),
    url(
        regex=r'^type/$',
        view=views.select_type,
        name='type'
    ),
    url(
        regex=r'^add/(?P<type>[\w.@+-]+)/$',
        view=views.create_project,
        name='add'
    ),
    url(
        regex=r'edit/(?P<type>[\w.@+-]+)/(?P<pk>[0-9]+)/$',
        view=views.edit_project,
        name='edit'
    ),
    url(
        regex=r'delete/(?P<pk>[0-9]+)/$',
        view=views.LinkingProjectDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'exec/(?P<pk>[0-9])/$',
        view=views.execute,
        name='exec'
    ),
    url(
        regex=r'results/(?P<pk>[0-9]+)/$',
        view=views.view_results,
        name='view_results'
    ),
    url(
        regex=r'export/(?P<pk>[0-9]+)/$',
        view=views.export_to_json,
        name='export'
    ),
    url(
        regex=r'stop/(?P<pk>[0-9]+)/$',
        view=views.stop_project,
        name='stop_project'
    ),
]

web-app/linkage/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

web-app/linkage/datasets/models.py
from __future__ import unicode_literals, absolute_import

import pandas as pd

from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
import os

COLUMN_TYPES = (
    ('BOOLEAN', 'Boolean'),
    ('REAL', 'Float'),
    ('INTEGER', 'Integer'),
    ('VARCHAR', 'String'),
)


@python_2_unicode_compatible
class Dataset(models.Model):
    dataset_formats = (
        ('CSV', 'Comma Separated Values'),
        # ('XLSX', 'Microsoft Excel file'),
        # ('JSON', 'JavaScript Object Notation'),
        # ('XML', 'XML')
    )

    path = os.environ.get('FILE_LOC', '/user_data/media/datasets/')

    #Traversing directory to load dataset or filename
    dataset_urls = ((file_name, file_name) for file_name in os.listdir(path) if file_name.lower().endswith(".csv"))


    name = models.CharField(_('Name of Dataset'), unique=True, max_length=512)
    description = models.TextField(_('Dataset description'), null=True,
                                   blank=True)
    format = models.CharField(_('Dataset Format'), max_length=6,
                              choices=dataset_formats, default='CSV')
    url = models.CharField(_('Name of the dataset file'), choices=dataset_urls, max_length=255)
    last_edit_date = models.DateField(_('Last edit date'), auto_now=True)

    data_types = JSONField(blank=True, null=True)
    field_cats = JSONField(blank=True, null=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_fields(self):
        if self.data_types:
            return list(self.data_types.keys())
        else:
            file_path = settings.DATASTORE_URL + self.url
            df = pd.read_csv(file_path, nrows=1)
            return list(df)

    def get_absolute_url(self):
        return reverse("datasets:edit", kwargs={"pk": self.pk})

web-app/linkage/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

web-app/linkage/datasets/forms.py
import logging
from django.forms import ModelForm, Textarea, TextInput, Select, ChoiceField, HiddenInput
from django.utils.translation import ugettext_lazy as _

from .models import Dataset

logger = logging.getLogger(__name__)


class DatasetForm(ModelForm):
    class Meta:
        model = Dataset
        fields = ['name', 'description', 'format', 'url']

        labels = {
            'name': _('Dataset Name'),
            'description': _('Description'),
            'format': _('File Format'),
            'url': _('File Name'),
        }
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'rows': 5, 'class': 'form-control'}),
            'format': Select(attrs={'class': 'form-control'}),
            'url': Select(attrs={'class': 'form-control'}),
        }


class DatasetUpdateForm(DatasetForm):
    class Meta(DatasetForm.Meta):

        fields = DatasetForm.Meta.fields + ['data_types', 'field_cats']

    def __init__(self, *args, **kwargs):
        super(DatasetUpdateForm, self).__init__(*args, **kwargs)

        if self.instance.pk:
            self.fields['data_types'].widget = HiddenInput()
            self.fields['field_cats'].widget = HiddenInput()

web-app/linkage/datasets/views.py
from __future__ import absolute_import

import json
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from linkage.taskapp.tasks import linkage_field_categories

from .forms import DatasetForm, DatasetUpdateForm
from .logic.preview import get_preview
from .models import Dataset, COLUMN_TYPES

logger = logging.getLogger(__name__)

FIELD_CATS = linkage_field_categories()


class DatasetPreviewMixin(object):
    preview_choices = (
        ('head', 'First rows'),
        ('tail', 'Last rows'),
        ('rand', 'Random Selection')
    )

    @property
    def preview(self):
        previewer = get_preview(self.filename, self.data_format)
        result = previewer.preview('head', 25,
                                   data_types=self.object.data_types)
        return {
            "len": result['len'],
            "header": result['header'],
            "rows": result['rows'],
            "preview_choices": self.preview_choices,
        }

    def get_context_data(self, **kwargs):
        context = super(DatasetPreviewMixin, self).get_context_data(**kwargs)
        self.data_format = 'csv'
        self.filename = context['object'].url

        context['preview'] = self.preview
        return context


class DatasetListView(LoginRequiredMixin, ListView):
    model = Dataset


class DatasetCreateView(LoginRequiredMixin, CreateView):
    model = Dataset
    form_class = DatasetForm

    def get_success_url(self):
        return reverse('datasets:edit', kwargs={'pk': self.object.pk})


class DatasetUpdateView(LoginRequiredMixin, UpdateView):
    model = Dataset
    form_class = DatasetUpdateForm

    def get_context_data(self, **kwargs):
        logger.info('Data type: %s', self.object.data_types)

        data = super(DatasetUpdateView, self).get_context_data(**kwargs)
        if not self.request.POST:
            data['data_types'] = self.object.data_types
            data['field_cats'] = self.object.field_cats
            data['COLUMN_TYPES'] = COLUMN_TYPES
            data['FIELD_CATS'] = FIELD_CATS
            previewer = get_preview(self.object.url, 'csv')
            result = previewer.preview('head', 4,
                                       data_types=self.object.data_types)
            data['columns'] = result['header']
            data['types'] = result['types']
            data['records'] = result['rows']
        return data

    def get_success_url(self):
        return reverse('datasets:list')


class DatasetDeleteView(LoginRequiredMixin, DeleteView):
    model = Dataset
    form_class = DatasetUpdateForm

    def get_success_url(self):
        return reverse('datasets:list')


class DatasetDetailView(LoginRequiredMixin, DatasetPreviewMixin, DetailView):
    model = Dataset


@csrf_protect
@login_required
def dataset_preview(request):
    filename = request.POST.get('filename')
    limit = request.POST.get('limit')
    criteria = request.POST.get('criteria')
    previewer = get_preview(filename, 'csv')
    result = previewer.preview(criteria, int(limit))
    data = {
        'header': result['header'],
        'rows': result['rows'],
    }

    return render(request, 'datasets/dataset_preview.html', {'preview': data})


@csrf_protect
@login_required
def dataset_header(request):
    id = request.GET.get('id', '')
    try:
        dataset = Dataset.objects.get(pk=id)
        fields = dataset.get_fields()
    except Dataset.DoesNotExist:
        logger.error('Database error. No dataset with id %s was found.', id)
        fields = None
    except ValueError:
        logger.error('Database error on fetching record data.')
        fields = None

    return HttpResponse(json.dumps({'header': fields}),
                        content_type="application/json")

web-app/linkage/shared/views.py
import os
import json
import logging

from django.shortcuts import render
from linkage.taskapp.tasks import linkage_linklib_info
from django.conf import settings

logger = logging.getLogger(__name__)

linkapp_info = linkage_linklib_info()


def get_source_commit():
    logger.info('ROOT_DIR: {0}, APP_DIR: {1}'.format(settings.ROOT_DIR, settings.APPS_DIR))
    source_commit_file = os.path.join(settings.ROOT_DIR(), 'git_commits.json')

    try:
        with open(source_commit_file) as commit_file:
            return json.load(commit_file)

    except OSError:
        return dict()


def about_view(request):

    logger.info('Application about page.')
    git_commits = get_source_commit()
    data = {
        'app_source': settings.LINKING_APP_SOURCE,
        'link_source': settings.LINKING_LIB_SOURCE,
        'app_version': settings.APP_VERSION,
        'link_version': linkapp_info.get('version'),
        'web_commit': git_commits.get('web_source_commit', ''),
        'link_commit': git_commits.get('link_source_commit', '')
    }

    return render(request, 'pages/about.html', {'data': data})

web-app/linkage/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

web-app/linkage/templates/datasets/dataset_confirm_delete.html
{% extends 'base.html' %}
{% block title %}{{object.name}} Dataset Delete?{% endblock %}

{% block content %}

    <legend><h3 class="text-danger">Delete {{ object }} Dataset?</h3></legend>
    <p>Are you sure you want to delete this dataset? Please confirm.</p>
    <div style="margin-top: 25px;">
        <form action="" method="post">
            {% csrf_token %}
            <input class="btn btn-default" type="button" value="Cancel" onclick="window.history.go(-1);"/>
            <input class="btn btn-danger pull-right" type="submit" value="Confirm"/>
        </form>
    </div>

{% endblock content %}

web-app/linkage/templates/datasets/dataset_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h2>{{ object.name }}</h2>
            {% if object.description %}
                <p>{{ object.description }}</p>
            {% endif %}
        </div>
    </div>

    <h2 class="form-signin-heading">Data Preview</h2>
    <form class="form-horizontal" id="preview-form">
        {{ csrf_input }}
        <div class="form-group">
            <label for="row-count" class="control-label col-sm-2">Total Records:</label>
            <div class="col-sm-4">
                <p class="form-control-static" id="row-count">{{ preview.len }}</p>
            </div>
            <label for="col-count" class="control-label col-sm-2">Total Columns:</label>
            <div class="col-sm-4">
                <p class="form-control-static" id="col-count">{{ preview.header|length }}</p>
            </div>
        </div>
        <div class="form-group">
            <label for="preview_size" class="control-label col-sm-2">Preview Size:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" value="25" id="preview_size"/>
            </div>
            <label for="rows_select" class="control-label col-sm-2">Selection Criteria:</label>
            <div class="col-sm-4">
                <select id="rows_select" class="form-control">
                    {% for choice in preview.preview_choices %}
                        <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group preview col-sm-12">
            <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-eye-open"></i> Preview</button>
        </div>
    </form>

    <div class="clearfix"></div>
    <div class="preview-container">
        <div id="preview-table-topscroll">
            <div class="preview-data" style="visibility: hidden;">
                {% include "datasets/dataset_preview.html" %}
            </div>
        </div>
        <div id="preview-table">
            <div class="preview-data">
                {% include "datasets/dataset_preview.html" %}
            </div>
        </div>
    </div>
{% endblock content %}
{% block javascript %}
    {{ block.super }}
    <script type="text/javascript">
        var filename = "{{ object.url }}";
        var dataset_name = "{{ object.name }}"
        var PREVIEW_URL = "{% url 'datasets:detail' pk='1' %}"
        PREVIEW_URL = PREVIEW_URL.substring(0, PREVIEW_URL.length - 2);
    </script>
    <script type="text/javascript" src="{% static 'js/datasets/preview.js' %}"></script>
{% endblock %}

web-app/linkage/templates/datasets/dataset_form.html
{% extends "base.html" %}
{% load static %}
{% load linking_extras %}
{% load jsonify %}

{% block content %}
    <legend><h2>Dataset</h2></legend>
    <div class="row">
        <form id="dataset-form" class="form-horizontal" method="post">
            {% csrf_token %}
            <label for="{{ form.name.id_for_label }}" class="control-label col-sm-3">{{ form.name.label }}</label>
            <div class="preview col-sm-9">
                {{ form.name }}
            </div>

            <label for="{{ form.description.id_for_label }}"
                   class="control-label col-sm-3">{{ form.description.label }}</label>
            <div class="preview col-sm-9">
                {{ form.description }}
            </div>

            <label for="{{ form.format.id_for_label }}"
                   class="control-label col-sm-3">{{ form.format.label }}</label>
            <div class="preview col-sm-9">
                {{ form.format }}
            </div>

            <label for="{{ form.url.id_for_label }}" class="control-label col-sm-3">{{ form.url.label }}</label>
            <div class="preview col-sm-9">
                {{ form.url }}
            </div>

            {% if form.instance.pk %}
                {{ form.data_types }}
                {{ form.field_cats }}
                <div class="col-sm-12">
                    <legend><h3>Data types</h3></legend>
                    <table id="header-type-table" class="table table-bordered">
                        <thead>
                            <th class="col-md-2">Field Name</th>
                            <th class="col-md-2">Field Type</th>
                            <!-- <th class="col-md-2">Field Category</th> -->
                            <th colspan="4">Sample Data</th>
                        </thead>
                        <tbody>
                        {% for field in columns %}
                            <tr>
                                <th class="col-md-2">{{ field }}</th>
                                <td>
                                    <select class="data-type form-control" id="{{ field }}_dtype">
                                    <option value=""></option>
                                        {% for type in COLUMN_TYPES %}
                                            <option value="{{ type.0 }}">{{ type.1 }}</option>
                                        {% endfor %}
                                    </select>
                                </td>
                                <!--
                                <td>
                                    <select class="field-cat form-control" id="{{ field }}_cat">
                                    <option value=""></option>
                                        {% for type in FIELD_CATS %}
                                            <option value="{{ type.0 }}">{{ type.1 }}</option>
                                        {% endfor %}
                                    </select>
                                </td>
                                -->
                                {%  with index=forloop.counter0 %}
                                    {% for row in records %}
                                        <td>{{ row|get_cell:index }}</td>
                                    {% endfor %}
                                {% endwith %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
            <div class="form-group preview col-sm-12">
                <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Save</button>
            </div>
        </form>
    </div>
{% endblock %}
{% block javascript %}
    {{ block.super }}
    <script type="text/javascript">
        var data_types = JSON.parse('{{ data_types | jsonify }}');
        var field_cats = JSON.parse('{{ field_cats | jsonify }}');
        var columns = "{{ columns }}";
        var COPLUMN_TYPES = "{{ COPLUMN_TYPES }}";
        var FIELD_CATS = "{{ FIELD_CATS }}";
        var header_types = JSON.parse('{{ types | jsonify }}');
    </script>
    <script src="{% static 'js/datasets/dataset_form.js' %}"></script>
{% endblock %}

web-app/linkage/templates/datasets/dataset_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Available Datasets{% endblock %}

{% block content %}
    <h2>Datasets</h2>
    <table class="table table-striped list-table">
        <thead>
            <tr>
                <th style="width: 250px;">Name</th>
                <th>Description</th>
                <th style="width: 125px;">Last Edited</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for dataset in dataset_list.all|dictsort:"name" %}
            <tr>
                <td style="border-right:solid #ddd 1px; vertical-align: middle !important;">
                    <a href="{% url 'datasets:edit' dataset.pk %}">{{ dataset.name }}</a>
                </td>
                <td style="border-right:solid #ddd 1px;">{{ dataset.description|truncatechars:100 }}</td>
                <td style="border-right:solid #ddd 1px;">{{ dataset.last_edit_date }}</td>
                <td style="border-right:solid #ddd 1px; width: 40px;" class="text-left">
                    <a href="{% url 'datasets:detail' dataset.pk %}" data-toggle="tooltip" title="Preview Dataset">
                        <i class="glyphicon glyphicon-eye-open"></i>
                    </a>
                </td>
                <td style="width: 40px;" class="text-right">
                    <a class="text-danger" href="{% url 'datasets:delete' dataset.pk %}" data-toggle="tooltip" title="Delete Dataset">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
        <tbody>
    </table>

    <div>
        <a href="{% url 'datasets:add' %}" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> Create New Dataset</a>
    </div>
{% endblock content %}

web-app/linkage/templates/datasets/dataset_preview.html
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            {% for field in preview.header %}
                <th>{{ field }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for record in preview.rows %}
            <tr>
                {% for item in record %}
                    <td>{{ item }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>