web-app/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from linkage.shared import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', view=views.about_view, name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('linkage.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Dataset exploration
    url(r'^datasets/', include('linkage.datasets.urls', namespace='datasets')),

    # Datsets Linking
    url(r'^linking/', include('linkage.linking.urls', namespace='linking')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=settings.SHOW_INDEXES)
#show indexs are for dev debugging purposes

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

web-app/linkage/datasets/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from linkage.datasets import views

urlpatterns = [
    url(
        regex=r'^preview/$',
        view=views.dataset_preview,
        name='get_preview'
    ),
    url(
        regex=r'^header/$',
        view=views.dataset_header,
        name='header'
    ),
    url(
        regex=r'^$',
        view=views.DatasetListView.as_view(),
        name='list'
    ),
    url(
        regex=r'add/$',
        view=views.DatasetCreateView.as_view(),
        name='add'
    ),
    url(
        regex=r'edit/(?P<pk>[0-9]+)/$',
        view=views.DatasetUpdateView.as_view(),
        name='edit'
    ),
    url(
        regex=r'delete/(?P<pk>[0-9]+)/$',
        view=views.DatasetDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^(?P<pk>[0-9]+)/$',
        view=views.DatasetDetailView.as_view(),
        name='detail'
    ),
 ]

web-app/linkage/linking/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from linkage.linking import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.LinkingProjectListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^status/$',
        view=views.AjaxListView.as_view(),
        name='status'
    ),
    url(
        regex=r'^type/$',
        view=views.select_type,
        name='type'
    ),
    url(
        regex=r'^add/(?P<type>[\w.@+-]+)/$',
        view=views.create_project,
        name='add'
    ),
    url(
        regex=r'edit/(?P<type>[\w.@+-]+)/(?P<pk>[0-9]+)/$',
        view=views.edit_project,
        name='edit'
    ),
    url(
        regex=r'delete/(?P<pk>[0-9]+)/$',
        view=views.LinkingProjectDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'exec/(?P<pk>[0-9])/$',
        view=views.execute,
        name='exec'
    ),
    url(
        regex=r'results/(?P<pk>[0-9]+)/$',
        view=views.view_results,
        name='view_results'
    ),
    url(
        regex=r'export/(?P<pk>[0-9]+)/$',
        view=views.export_to_json,
        name='export'
    ),
    url(
        regex=r'stop/(?P<pk>[0-9]+)/$',
        view=views.stop_project,
        name='stop_project'
    ),
]

web-app/linkage/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

web-app/linkage/linking/models.py
from __future__ import unicode_literals

from django.contrib.postgres.fields import JSONField
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from linkage.datasets.models import Dataset


PROJECT_TYPES = (
    ('DEDUP', 'De-Duplication'),
    ('LINK', 'Data Linkage')
)

LINKING_METHODS = (
    ('DTR', 'Deterministic'),
    ('PRB', 'Probabilistic'),
)

LINKING_RELATIONSHIPS = (
    ('1T1', 'One to One'),
    ('1TM', 'One to Many'),
    ('MT1', 'Many to One'),
)

PROJECT_STATUS = (
    ('DRAFT', 'Draft'),
    ('READY', 'Ready'),
    ('RUNNING', 'In Progress'),
    ('COMPLETED', 'Completed'),
    ('FAILED', 'Failed'),
)


class LinkingProject(models.Model):
    name = models.CharField(_('Lnking project name'), unique=True, max_length=512)
    type = models.CharField(_('Project Type'), max_length=10, choices=PROJECT_TYPES, default='LINK')
    description = models.TextField(_('Linking Project description'), blank=True)
    relationship_type = models.CharField(_('Linking Relationship type'), max_length=3, choices=LINKING_RELATIONSHIPS,
                                         default='1T1')
    linked_url = models.URLField(_('Linked output file'))
    matched_url = models.URLField(_('Matched but not linked records file'))
    results_file = models.CharField(_('Project summary file'), max_length=255, blank=True)
    datasets = models.ManyToManyField(Dataset, through='LinkingDataset')
    status = models.CharField(_('Project Status'), max_length=10, choices=PROJECT_STATUS, default='DRAFT')
    task_id = models.CharField(_('Project task id'), max_length=255, blank=True)
    comments = models.TextField(_('Comments'), blank=True)
    last_edit_date = models.DateField(_('Last edit date'), auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("linking:edit", kwargs={"pk": self.pk})


class LinkingDataset(models.Model):
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
    link_project = models.ForeignKey(LinkingProject, on_delete=models.CASCADE)
    link_seq = models.IntegerField()
    columns = JSONField(blank=True, null=True)
    index_field = models.CharField(_('Index Field'), max_length=255)
    entity_field = models.CharField(_('Entity identifier Field'), max_length=255, blank=True, null=True)

    class Meta:
        ordering = ['link_seq']


@python_2_unicode_compatible
class LinkingStep(models.Model):
    seq = models.IntegerField()
    blocking_schema = JSONField()
    linking_schema = JSONField()
    group = models.BooleanField(_('Dedup Entity Group Flag'), default=True)
    linking_project = models.ForeignKey(LinkingProject, related_name='steps', on_delete=models.CASCADE)
    linking_method = models.CharField(_('Linking Method'), max_length=3, choices=LINKING_METHODS, default='DTR')

    def __str__(self):
        return 'Linking step {0} of linking project {}.'.format(self.seq, self.linking_project)

    class Meta:
        ordering = ['seq']

web-app/linkage/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

web-app/linkage/datasets/forms.py
import logging
from django.forms import ModelForm, Textarea, TextInput, Select, ChoiceField, HiddenInput
from django.utils.translation import ugettext_lazy as _

from .models import Dataset

logger = logging.getLogger(__name__)


class DatasetForm(ModelForm):
    class Meta:
        model = Dataset
        fields = ['name', 'description', 'format', 'url']

        labels = {
            'name': _('Dataset Name'),
            'description': _('Description'),
            'format': _('File Format'),
            'url': _('File Name'),
        }
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'rows': 5, 'class': 'form-control'}),
            'format': Select(attrs={'class': 'form-control'}),
            'url': Select(attrs={'class': 'form-control'}),
        }


class DatasetUpdateForm(DatasetForm):
    class Meta(DatasetForm.Meta):

        fields = DatasetForm.Meta.fields + ['data_types', 'field_cats']

    def __init__(self, *args, **kwargs):
        super(DatasetUpdateForm, self).__init__(*args, **kwargs)

        if self.instance.pk:
            self.fields['data_types'].widget = HiddenInput()
            self.fields['field_cats'].widget = HiddenInput()

web-app/linkage/datasets/views.py
from __future__ import absolute_import

import json
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from linkage.taskapp.tasks import linkage_field_categories

from .forms import DatasetForm, DatasetUpdateForm
from .logic.preview import get_preview
from .models import Dataset, COLUMN_TYPES

logger = logging.getLogger(__name__)

FIELD_CATS = linkage_field_categories()


class DatasetPreviewMixin(object):
    preview_choices = (
        ('head', 'First rows'),
        ('tail', 'Last rows'),
        ('rand', 'Random Selection')
    )

    @property
    def preview(self):
        previewer = get_preview(self.filename, self.data_format)
        result = previewer.preview('head', 25,
                                   data_types=self.object.data_types)
        return {
            "len": result['len'],
            "header": result['header'],
            "rows": result['rows'],
            "preview_choices": self.preview_choices,
        }

    def get_context_data(self, **kwargs):
        context = super(DatasetPreviewMixin, self).get_context_data(**kwargs)
        self.data_format = 'csv'
        self.filename = context['object'].url

        context['preview'] = self.preview
        return context


class DatasetListView(LoginRequiredMixin, ListView):
    model = Dataset


class DatasetCreateView(LoginRequiredMixin, CreateView):
    model = Dataset
    form_class = DatasetForm

    def get_success_url(self):
        return reverse('datasets:edit', kwargs={'pk': self.object.pk})


class DatasetUpdateView(LoginRequiredMixin, UpdateView):
    model = Dataset
    form_class = DatasetUpdateForm

    def get_context_data(self, **kwargs):
        logger.info('Data type: %s', self.object.data_types)

        data = super(DatasetUpdateView, self).get_context_data(**kwargs)
        if not self.request.POST:
            data['data_types'] = self.object.data_types
            data['field_cats'] = self.object.field_cats
            data['COLUMN_TYPES'] = COLUMN_TYPES
            data['FIELD_CATS'] = FIELD_CATS
            previewer = get_preview(self.object.url, 'csv')
            result = previewer.preview('head', 4,
                                       data_types=self.object.data_types)
            data['columns'] = result['header']
            data['types'] = result['types']
            data['records'] = result['rows']
        return data

    def get_success_url(self):
        return reverse('datasets:list')


class DatasetDeleteView(LoginRequiredMixin, DeleteView):
    model = Dataset
    form_class = DatasetUpdateForm

    def get_success_url(self):
        return reverse('datasets:list')


class DatasetDetailView(LoginRequiredMixin, DatasetPreviewMixin, DetailView):
    model = Dataset


@csrf_protect
@login_required
def dataset_preview(request):
    filename = request.POST.get('filename')
    limit = request.POST.get('limit')
    criteria = request.POST.get('criteria')
    previewer = get_preview(filename, 'csv')
    result = previewer.preview(criteria, int(limit))
    data = {
        'header': result['header'],
        'rows': result['rows'],
    }

    return render(request, 'datasets/dataset_preview.html', {'preview': data})


@csrf_protect
@login_required
def dataset_header(request):
    id = request.GET.get('id', '')
    try:
        dataset = Dataset.objects.get(pk=id)
        fields = dataset.get_fields()
    except Dataset.DoesNotExist:
        logger.error('Database error. No dataset with id %s was found.', id)
        fields = None
    except ValueError:
        logger.error('Database error on fetching record data.')
        fields = None

    return HttpResponse(json.dumps({'header': fields}),
                        content_type="application/json")

web-app/linkage/shared/views.py
import os
import json
import logging

from django.shortcuts import render
from linkage.taskapp.tasks import linkage_linklib_info
from django.conf import settings

logger = logging.getLogger(__name__)

linkapp_info = linkage_linklib_info()


def get_source_commit():
    logger.info('ROOT_DIR: {0}, APP_DIR: {1}'.format(settings.ROOT_DIR, settings.APPS_DIR))
    source_commit_file = os.path.join(settings.ROOT_DIR(), 'git_commits.json')

    try:
        with open(source_commit_file) as commit_file:
            return json.load(commit_file)

    except OSError:
        return dict()


def about_view(request):

    logger.info('Application about page.')
    git_commits = get_source_commit()
    data = {
        'app_source': settings.LINKING_APP_SOURCE,
        'link_source': settings.LINKING_LIB_SOURCE,
        'app_version': settings.APP_VERSION,
        'link_version': linkapp_info.get('version'),
        'web_commit': git_commits.get('web_source_commit', ''),
        'link_commit': git_commits.get('link_source_commit', '')
    }

    return render(request, 'pages/about.html', {'data': data})

web-app/linkage/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

web-app/linkage/templates/linking/blocking_vars.html
{% load linking_extras %}
{% if form.id.value %}
    {% for left, right, alg in blocking_schema|get_item:form.seq.value %}
        <div class="block-var-row">
            <div class="row required">
                <label for="block_id_left_{{ form_index }}_{{ forloop.counter0 }}" class="control-label col-sm-2">Left
                    Variable</label>
                <div class="preview col-sm-4">
                    <select id="block_id_left_{{ form_index }}_{{ forloop.counter0 }}"
                            class="left-header left-blocking-var form-control"
                            name="block_id_left_{{ form_index }}_{{ forloop.counter0 }}">
                        <option value="{{ left }}" selected="selected">{{ left }}</option>
                    </select>
                </div>
                <label for="block_id_right_{{ form_index }}_{{ forloop.counter0 }}" class="control-label col-sm-2">Right
                    Variable</label>
                <div class="preview col-sm-4">
                    <select id="block_id_right_{{ form_index }}_{{ forloop.counter0 }}"
                            {% if type == 'DEDUP' %}
                                class="left-header right-blocking-var form-control"
                            {% else %}
                                class="right-header right-blocking-var form-control"
                            {% endif %}
                            name="block_id_right_{{ form_index }}_{{ forloop.counter0 }}">
                        <option value="{{ right }}" selected="selected">{{ right }}</option>
                    </select>
                </div>
            </div>
            <div class="row required">
                <label for="block_comp_{{ form_index }}_{{ forloop.counter0 }}"
                       class="control-label col-sm-2">Transformation</label>
                <div class="col-sm-10">
                    <div class="preview input-group">
                        <select id="block_comp_{{ form_index }}_{{ forloop.counter0 }}" class="alg form-control"
                                name="block_comp_{{ form_index }}_{{ forloop.counter0 }}">
                            <option value=""></option>
                            {% for item in blocking_transformation_choices %}
                                <option value="{{ item.0 }}" {% if alg == item.0 %}
                                        selected="selected" {% endif %}>{{ item.1 }}</option>
                            {% endfor %}
                        </select>
                        <div class="input-group-btn">
                            <button type="button" class="blocking-var-remove btn btn-danger">
                                <i class="glyphicon glyphicon-remove"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}

web-app/linkage/templates/linking/dataset_header_list.html
<select class="form-control">
    {% for value in left_header %}
        <option value="{{ value }}">{{ value }}</option>
    {% endfor %}
</select>

web-app/linkage/templates/linking/dedup_linking_vars.html
{% load linking_extras %}
{% if form.id.value %}
    {% for left, right, alg in linking_schema|get_item:form.seq.value %}
        <div class="link-var-row">
            <div class="row">
                <label for="link_id_left_{{ form_index }}_{{ forloop.counter0 }}" class="control-label col-sm-2">Left
                    Variable</label>
                <div class="preview col-sm-4">
                    <select id="link_id_left_{{ form_index }}_{{ forloop.counter0 }}"
                            class="left-header left-link-var form-control"
                            name="link_id_left_{{ form_index }}_{{ forloop.counter0 }}">
                        <option value="{{ left }}" selected="selected">{{ left }}</option>
                    </select>
                </div>
                <label for="link_id_right_{{ form_index }}_{{ forloop.counter0 }}" class="control-label col-sm-2">Right
                    Variable</label>
                <div class="preview col-sm-4">
                    <select id="link_id_right_{{ form_index }}_{{ forloop.counter0 }}"
                            class="left-header right-link-var form-control"
                            name="link_id_right_{{ form_index }}_{{ forloop.counter0 }}">
                        <option value="{{ right }}" selected="selected">{{ right }}</option>
                    </select>
                </div>
            </div>
            {% include "linking/comparison_methods.html" %}
        </div>
    {% endfor %}
{% endif %}

web-app/linkage/templates/linking/dedupproject_form.html
{% extends "./project_form.html" %}
{% load static %}

{% block header %}
    <legend><h2>De-Duplication Project</h2></legend>
{% endblock %}

{% block datasets %}
    <fieldset>
        <div class="row required">
            <label for="{{ form.left_data.id_for_label }}" class="control-label col-sm-2">{{ form.left_data.label }}</label>
            <div class="preview col-sm-4">
                {{ form.left_data }}
            </div>
            <label for="{{ form.left_index.id_for_label }}"
                   class="control-label col-sm-2">{{ form.left_index.label }}</label>
            <div class="preview col-sm-4">
                <select name="left_index" id="id_left_index"
                        class="left-header form-control">
                    {% if form.left_index.value %}
                        <option value="{{ form.left_index.value }}" selected="selected">
                                {{ form.left_index.value }}</option>
                    {% endif %}
                </select>
            </div>
        </div>
    </fieldset>
{% endblock %}

web-app/linkage/templates/linking/link_linking_variables.html
{% load linking_extras %}
{% if form.id.value %}
    {% for left, right, alg in linking_schema|get_item:form.seq.value %}
        <div class="link-var-row">
            <div class="row">
                <label for="link_id_left_{{ form_index }}_{{ forloop.counter0 }}" class="control-label col-sm-2">Left
                    Variable</label>
                <div class="preview col-sm-4">
                    <select id="link_id_left_{{ form_index }}_{{ forloop.counter0 }}"
                            class="left-header left-link-var form-control"
                            name="link_id_left_{{ form_index }}_{{ forloop.counter0 }}">
                        <option value="{{ left }}" selected="selected">{{ left }}</option>
                    </select>
                </div>
                <label for="link_id_right_{{ form_index }}_{{ forloop.counter0 }}" class="control-label col-sm-2">Right
                    Variable</label>
                <div class="preview col-sm-4">
                    <select id="link_id_right_{{ form_index }}_{{ forloop.counter0 }}"
                            class="right-header right-link-var form-control"
                            name="link_id_right_{{ form_index }}_{{ forloop.counter0 }}">
                        <option value="{{ right }}" selected="selected">{{ right }}</option>
                    </select>
                </div>
            </div>
            {% include "linking/comparison_methods.html" %}
        </div>
    {% endfor %}
{% endif %}

web-app/linkage/templates/linking/project_form.html
{% extends "base.html" %}
{% load static %}
{% load jsonify %}

{% block content %}
    {% block header %}{% endblock %}
    <p id="project-title" class="hidden"></p>
    <form class="form-horizontal" id="linking-form" method="post">
        {% csrf_token %}
        {% if type == 'LINK' %}
            {{ form.right_columns }}
        {% endif %}
        {{ form.left_columns }}
        <ul class="nav nav-tabs" id="project-tabs">
            <li role="presentation" class="active" id="tab-main"><a href="#project-main-tab" data-toggle="tab">General</a></li>
            <li role="presentation" class="disabled" id="tab-steps"><a href="#project-steps" data-toggle="tab">Steps</a></li>
            <li role="presentation" class="disabled" id="tab-results"><a href="#project-results" data-toggle="tab">Results</a></li>
        </ul>
        <div class="tab-content" id="project-tab-content">
            <div class="tab-pane active" id="project-main-tab">
                {% block main_fields %}
                    {{ form.status }}
                    <div class="row required">
                        <label for="{{ form.name.id_for_label }}" class="control-label col-sm-2">{{ form.name.label }}</label>
                        <div class="preview col-sm-10">
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="row">
                        <label for="{{ form.description.id_for_label }}" class="control-label col-sm-2">{{ form.description.label }}</label>
                        <div class="preview col-sm-10">
                            {{ form.description }}
                        </div>
                    </div>
                {% endblock %}
                {% block datasets %}{% endblock %}
            </div>
            <div class="tab-pane" id="project-steps">
                <fieldset>
                    {% if form.name.value %}
                        <div id="form-steps-container">
                            {% include "linking/linking_step_form.html" %}
                        </div>
                        <div class="pull-right">
                            <a id="step-create" href="" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> Add Step</a>
                        </div>
                    {% endif %}
                </fieldset>
            </div>
            <div class="tab-pane" id="project-results">
                {% include "linking/linking_results_form.html" %}
            </div>
        </div>
        <div class="form-group preview col-sm-12" style="margin-top: 20px;">
            <button type="submit" class="btn btn-primary hidden" id="project-create"><i class="glyphicon glyphicon-plus"></i> Create</button>
            <button type="submit" class="btn btn-primary hidden" id="project-save"><i class="glyphicon glyphicon-floppy-disk"></i> Save</button>
            <button type="button" class="btn btn-info hidden disabled" id="step-continue">Continue</button>
        </div>
    </form>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript">
       var left_data_id = "{{ form.left_data.id_for_label }}";
       var DATASET_COLUMNS_URL = "{% url 'datasets:header' %}";
       var COMPARISON_ARGS = JSON.parse('{{ comparison_args | jsonify }}');
       var header_options = {};
       header_options[left_data_id] = '';
       var transformation_choices = JSON.parse('{{ blocking_transformation_choices | jsonify }}');
       var comparison_choices = JSON.parse('{{ linking_comparison_choices | jsonify }}');
       var comparison_args = JSON.parse('{{ comparison_args | jsonify }}');
       var leftColumns = JSON.parse('{{ form.left_columns.value | jsonify }}') || [];
       var required_left = JSON.parse('{{ required_left  | jsonify }}') || [];
       var project_type = '{{ type }}';
    </script>
    <script type='text/javascript' src="{% static 'js/linking/project_form.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/linking/step_form.js' %}"></script>
{% endblock %}

web-app/linkage/templates/linking/projects_list.html
<table class="table table-striped list-table">
    <thead>
    <tr>
        <th style="width: 250px;">Name</th>
        <th>Description</th>
        <th>Type</th>
        <th>Status</th>
        <th style="width: 125px;">Last Edited</th>
        <th colspan="4">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for project in linkingproject_list.all|dictsort:"name" %}
        <tr>
            <td style="border-right:solid #ddd 1px; vertical-align: middle !important;" class="name-cell" {% if project.status == 'FAILED' %}rowspan="2"{% endif %}>
                <a href="{% url 'linking:edit' project.type project.pk %}">{{ project.name }}</a>
            </td>
            <td style="border-right:solid #ddd 1px;" class="description-cell">{{ project.description|truncatechars:100 }}</td>
            <td style="border-right:solid #ddd 1px;" class="type-cell">{{ project.type }}</td>
            <td style="border-right:solid #ddd 1px;" class="status-cell">{{ project.status }}</td>
            <td style="border-right:solid #ddd 1px;">{{ project.last_edit_date }}</td>
            <td style="width: 40px" class="exec-cell text-left">
                {% if project.status == 'RUNNING'%}
                    <a class="project-exec" href="{% url 'linking:stop_project' project.pk %}" data-toggle="tooltip" title="Stop Project">
                        <i class="glyphicon glyphicon-stop"></i>
                    </a>
                {% elif project.status != 'DRAFT' %}
                    <a class="project-exec" href="{% url 'linking:exec' project.pk %}" data-toggle="tooltip" title="Run Project">
                        <i class="glyphicon glyphicon-play-circle"></i>
                    </a>
                {% endif %}
            </td>
            <td style="width: 40px" class="text-center">
                {% if project.status == 'COMPLETED' %}
                    <a class="results-view" href="{% url 'linking:view_results' project.pk %}" data-toggle="tooltip" title="View Results">
                        <i class="glyphicon glyphicon-equalizer"></i>
                    </a>
                {% endif %}
            </td>
            <td style="border-right:solid #ddd 1px; width: 40px" class="action-cell text-right">
                {% if project.status != 'DRAFT' %}
                    <a href="{% url 'linking:export' project.pk %}" data-toggle="tooltip" title="Export to JSON">
                        <i class="glyphicon glyphicon-export"></i>
                    </a>
                {% endif %}
            </td>
            <td style="width: 40px;" class="action-cell text-right">
                <a class="text-danger" href="{% url 'linking:delete' project.pk %}" data-toggle="tooltip" title="Delete Project">
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
            </td>
        </tr>
        {% if project.status == 'FAILED' %}
            <tr class="danger">
                <td style="border-top:none;" colspan="6"><span style="display:block;width:250px;word-wrap:break-word; color: #800000;"><Strong>Error: </Strong>{{ project.comments }}</span></td>
            </tr>
        {% endif %}
    {% endfor %}
    <tbody>
</table>

<script type="text/javascript">
    total_running = parseInt("{{ total_running }}");
</script>