web-app/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from linkage.shared import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', view=views.about_view, name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('linkage.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Dataset exploration
    url(r'^datasets/', include('linkage.datasets.urls', namespace='datasets')),

    # Datsets Linking
    url(r'^linking/', include('linkage.linking.urls', namespace='linking')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=settings.SHOW_INDEXES)
#show indexs are for dev debugging purposes

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

web-app/linkage/datasets/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from linkage.datasets import views

urlpatterns = [
    url(
        regex=r'^preview/$',
        view=views.dataset_preview,
        name='get_preview'
    ),
    url(
        regex=r'^header/$',
        view=views.dataset_header,
        name='header'
    ),
    url(
        regex=r'^$',
        view=views.DatasetListView.as_view(),
        name='list'
    ),
    url(
        regex=r'add/$',
        view=views.DatasetCreateView.as_view(),
        name='add'
    ),
    url(
        regex=r'edit/(?P<pk>[0-9]+)/$',
        view=views.DatasetUpdateView.as_view(),
        name='edit'
    ),
    url(
        regex=r'delete/(?P<pk>[0-9]+)/$',
        view=views.DatasetDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^(?P<pk>[0-9]+)/$',
        view=views.DatasetDetailView.as_view(),
        name='detail'
    ),
 ]

web-app/linkage/linking/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from linkage.linking import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.LinkingProjectListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^status/$',
        view=views.AjaxListView.as_view(),
        name='status'
    ),
    url(
        regex=r'^type/$',
        view=views.select_type,
        name='type'
    ),
    url(
        regex=r'^add/(?P<type>[\w.@+-]+)/$',
        view=views.create_project,
        name='add'
    ),
    url(
        regex=r'edit/(?P<type>[\w.@+-]+)/(?P<pk>[0-9]+)/$',
        view=views.edit_project,
        name='edit'
    ),
    url(
        regex=r'delete/(?P<pk>[0-9]+)/$',
        view=views.LinkingProjectDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'exec/(?P<pk>[0-9])/$',
        view=views.execute,
        name='exec'
    ),
    url(
        regex=r'results/(?P<pk>[0-9]+)/$',
        view=views.view_results,
        name='view_results'
    ),
    url(
        regex=r'export/(?P<pk>[0-9]+)/$',
        view=views.export_to_json,
        name='export'
    ),
    url(
        regex=r'stop/(?P<pk>[0-9]+)/$',
        view=views.stop_project,
        name='stop_project'
    ),
]

web-app/linkage/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

web-app/linkage/datasets/models.py
from __future__ import unicode_literals, absolute_import

import pandas as pd

from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
import os

COLUMN_TYPES = (
    ('BOOLEAN', 'Boolean'),
    ('REAL', 'Float'),
    ('INTEGER', 'Integer'),
    ('VARCHAR', 'String'),
)


@python_2_unicode_compatible
class Dataset(models.Model):
    dataset_formats = (
        ('CSV', 'Comma Separated Values'),
        # ('XLSX', 'Microsoft Excel file'),
        # ('JSON', 'JavaScript Object Notation'),
        # ('XML', 'XML')
    )

    path = os.environ.get('FILE_LOC', '/user_data/media/datasets/')

    #Traversing directory to load dataset or filename
    dataset_urls = ((file_name, file_name) for file_name in os.listdir(path) if file_name.lower().endswith(".csv"))


    name = models.CharField(_('Name of Dataset'), unique=True, max_length=512)
    description = models.TextField(_('Dataset description'), null=True,
                                   blank=True)
    format = models.CharField(_('Dataset Format'), max_length=6,
                              choices=dataset_formats, default='CSV')
    url = models.CharField(_('Name of the dataset file'), choices=dataset_urls, max_length=255)
    last_edit_date = models.DateField(_('Last edit date'), auto_now=True)

    data_types = JSONField(blank=True, null=True)
    field_cats = JSONField(blank=True, null=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_fields(self):
        if self.data_types:
            return list(self.data_types.keys())
        else:
            file_path = settings.DATASTORE_URL + self.url
            df = pd.read_csv(file_path, nrows=1)
            return list(df)

    def get_absolute_url(self):
        return reverse("datasets:edit", kwargs={"pk": self.pk})

web-app/linkage/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

web-app/linkage/datasets/forms.py
import logging
from django.forms import ModelForm, Textarea, TextInput, Select, ChoiceField, HiddenInput
from django.utils.translation import ugettext_lazy as _

from .models import Dataset

logger = logging.getLogger(__name__)


class DatasetForm(ModelForm):
    class Meta:
        model = Dataset
        fields = ['name', 'description', 'format', 'url']

        labels = {
            'name': _('Dataset Name'),
            'description': _('Description'),
            'format': _('File Format'),
            'url': _('File Name'),
        }
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'rows': 5, 'class': 'form-control'}),
            'format': Select(attrs={'class': 'form-control'}),
            'url': Select(attrs={'class': 'form-control'}),
        }


class DatasetUpdateForm(DatasetForm):
    class Meta(DatasetForm.Meta):

        fields = DatasetForm.Meta.fields + ['data_types', 'field_cats']

    def __init__(self, *args, **kwargs):
        super(DatasetUpdateForm, self).__init__(*args, **kwargs)

        if self.instance.pk:
            self.fields['data_types'].widget = HiddenInput()
            self.fields['field_cats'].widget = HiddenInput()

web-app/linkage/datasets/views.py
from __future__ import absolute_import

import json
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from linkage.taskapp.tasks import linkage_field_categories

from .forms import DatasetForm, DatasetUpdateForm
from .logic.preview import get_preview
from .models import Dataset, COLUMN_TYPES

logger = logging.getLogger(__name__)

FIELD_CATS = linkage_field_categories()


class DatasetPreviewMixin(object):
    preview_choices = (
        ('head', 'First rows'),
        ('tail', 'Last rows'),
        ('rand', 'Random Selection')
    )

    @property
    def preview(self):
        previewer = get_preview(self.filename, self.data_format)
        result = previewer.preview('head', 25,
                                   data_types=self.object.data_types)
        return {
            "len": result['len'],
            "header": result['header'],
            "rows": result['rows'],
            "preview_choices": self.preview_choices,
        }

    def get_context_data(self, **kwargs):
        context = super(DatasetPreviewMixin, self).get_context_data(**kwargs)
        self.data_format = 'csv'
        self.filename = context['object'].url

        context['preview'] = self.preview
        return context


class DatasetListView(LoginRequiredMixin, ListView):
    model = Dataset


class DatasetCreateView(LoginRequiredMixin, CreateView):
    model = Dataset
    form_class = DatasetForm

    def get_success_url(self):
        return reverse('datasets:edit', kwargs={'pk': self.object.pk})


class DatasetUpdateView(LoginRequiredMixin, UpdateView):
    model = Dataset
    form_class = DatasetUpdateForm

    def get_context_data(self, **kwargs):
        logger.info('Data type: %s', self.object.data_types)

        data = super(DatasetUpdateView, self).get_context_data(**kwargs)
        if not self.request.POST:
            data['data_types'] = self.object.data_types
            data['field_cats'] = self.object.field_cats
            data['COLUMN_TYPES'] = COLUMN_TYPES
            data['FIELD_CATS'] = FIELD_CATS
            previewer = get_preview(self.object.url, 'csv')
            result = previewer.preview('head', 4,
                                       data_types=self.object.data_types)
            data['columns'] = result['header']
            data['types'] = result['types']
            data['records'] = result['rows']
        return data

    def get_success_url(self):
        return reverse('datasets:list')


class DatasetDeleteView(LoginRequiredMixin, DeleteView):
    model = Dataset
    form_class = DatasetUpdateForm

    def get_success_url(self):
        return reverse('datasets:list')


class DatasetDetailView(LoginRequiredMixin, DatasetPreviewMixin, DetailView):
    model = Dataset


@csrf_protect
@login_required
def dataset_preview(request):
    filename = request.POST.get('filename')
    limit = request.POST.get('limit')
    criteria = request.POST.get('criteria')
    previewer = get_preview(filename, 'csv')
    result = previewer.preview(criteria, int(limit))
    data = {
        'header': result['header'],
        'rows': result['rows'],
    }

    return render(request, 'datasets/dataset_preview.html', {'preview': data})


@csrf_protect
@login_required
def dataset_header(request):
    id = request.GET.get('id', '')
    try:
        dataset = Dataset.objects.get(pk=id)
        fields = dataset.get_fields()
    except Dataset.DoesNotExist:
        logger.error('Database error. No dataset with id %s was found.', id)
        fields = None
    except ValueError:
        logger.error('Database error on fetching record data.')
        fields = None

    return HttpResponse(json.dumps({'header': fields}),
                        content_type="application/json")

web-app/linkage/shared/views.py
import os
import json
import logging

from django.shortcuts import render
from linkage.taskapp.tasks import linkage_linklib_info
from django.conf import settings

logger = logging.getLogger(__name__)

linkapp_info = linkage_linklib_info()


def get_source_commit():
    logger.info('ROOT_DIR: {0}, APP_DIR: {1}'.format(settings.ROOT_DIR, settings.APPS_DIR))
    source_commit_file = os.path.join(settings.ROOT_DIR(), 'git_commits.json')

    try:
        with open(source_commit_file) as commit_file:
            return json.load(commit_file)

    except OSError:
        return dict()


def about_view(request):

    logger.info('Application about page.')
    git_commits = get_source_commit()
    data = {
        'app_source': settings.LINKING_APP_SOURCE,
        'link_source': settings.LINKING_LIB_SOURCE,
        'app_version': settings.APP_VERSION,
        'link_version': linkapp_info.get('version'),
        'web_commit': git_commits.get('web_source_commit', ''),
        'link_commit': git_commits.get('link_source_commit', '')
    }

    return render(request, 'pages/about.html', {'data': data})

web-app/linkage/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

web-app/linkage/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

web-app/linkage/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Ligo Linking{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
        <!-- Bootstrap 3 CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

        <!-- Third-party CSS libraries go here -->
        <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/select2-bootstrap.min.css' %}">

        <!-- This file stores project-specific CSS -->
        <link rel="stylesheet" href="{% static 'css/project.css' %}">
        <link rel="stylesheet" href="{% static 'css/datasets.css' %}">
        <link rel="stylesheet" href="{% static 'css/toggle_switch.css' %}">
    {% endblock %}{{ form.media.css }}
</head>

<body>
    <nav class="navbar navbar-inverse" style="background-color: #0D3A4F">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#cdi-linking-navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Ligo Linking</a>
            </div>
            <div class="collapse navbar-collapse" id="cdi-linking-navbar-collapse">
                <ul class="nav navbar-nav">
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'datasets:list' %}">Datasets</a></li>
                        <li><a href="{% url 'linking:list' %}">Projects</a></li>
                    {% endif %}
                    <li><a href="{% url 'about' %}">About</a></li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a>
                        </li>
                        <li>
                            <a href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                        </li>
                    {% else %}
                        <li>
                            <a id="log-in-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block messages %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endblock %}

        {% block content %}{% endblock content %}
    </div>

    {% block modal %}{% endblock modal %}

    <!-- Javascript placed at the end of the document so the pages load faster -->
    {% block javascript %}
        <script type='text/javascript' src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script type='text/javascript' src="{% static 'js/js.cookie-2.1.4.min.js' %}"></script>
        <script type='text/javascript' src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- Your stuff: Third-party javascript libraries go here -->
        <script type='text/javascript' src="{% static 'js/select2.min.js' %}"></script>

        <!-- place project specific Javascript in this file -->
        <script type='text/javascript' src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}{{ form.media.js }}
</body>
</html>